# Frametee Configuration (https://github.com/Teero888/frametee)

[keybinds]
dummy_fire = "MouseLeft"

[mouse]
sensitivity = 80.00
max_distance = 421.00

[graphics]
vsync = false
show_fps = true
fps_limit = 500
lod_bias = -0.60
bg_color = [0.275, 0.292, 0.311]
prediction_alpha = [1.000, 1.000]
center_dot = false
